const AppRoutes = {
  HOME: 'HOMESCREEN',
  DETAIL: 'DETAILSCREEN',
  CART: 'CARTSCREEN',
  ORDERS: 'ORDERSSCREEN',
  FAVORITES: 'FAVORITESSCREEN',
  PROFILE: 'PROFILESCREEN',
  TAB: 'TAB',
};

export default AppRoutes;
